os: linux
dist: xenial
language: java

addons:
  apt:
    packages:
      - libibverbs-dev
      - libibmad-dev
      - libibumad-dev
      - libibnetdisc-dev
      - libopensm-dev

stages:
  - name: build
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      script: ./gradlew cmakeBuild jar
    - stage: release
      script: ./gradlew publish -Dgpr.user=${GPR_USER} -Dgpr.token=${GPR_TOKEN} -Drelease=true

before_deploy: ./gradlew cmakeBuild jar -Drelease=true

deploy:
  provider: releases
  token: ${ACCESS_TOKEN}
  file: build/libs/jdetector-${TRAVIS_TAG}.jar
  cleanup: false
  overwrite: true
  on:
    repo: hhu-bsinfo/jdetector
    branch: master
    tags: true
