/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_jibperf_lib_IbFabric */

#ifndef _Included_de_hhu_bsinfo_jibperf_lib_IbFabric
#define _Included_de_hhu_bsinfo_jibperf_lib_IbFabric
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbFabric
 * Method:    init
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbFabric_init
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbFabric
 * Method:    refreshCounters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbFabric_refreshCounters
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbFabric
 * Method:    resetCounters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbFabric_resetCounters
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbFabric
 * Method:    getNumNodes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbFabric_getNumNodes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
