/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_jibperf_lib_IbNode */

#ifndef _Included_de_hhu_bsinfo_jibperf_lib_IbNode
#define _Included_de_hhu_bsinfo_jibperf_lib_IbNode
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    resetCounters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_resetCounters
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    refreshCounters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_refreshCounters
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getXmitDataBytes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getXmitDataBytes
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getRcvDataBytes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getRcvDataBytes
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getXmitPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getXmitPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getRcvPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getRcvPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getUnicastXmitPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getUnicastXmitPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getUnicastRcvPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getUnicastRcvPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getMulticastXmitPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getMulticastXmitPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getMulticastRcvPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getMulticastRcvPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getSymbolErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getSymbolErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getLinkDownedCounter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getLinkDownedCounter
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getLinkRecoveryCounter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getLinkRecoveryCounter
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getRcvErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getRcvErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getRcvRemotePhysicalErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getRcvRemotePhysicalErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getRcvSwitchRelayErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getRcvSwitchRelayErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getXmitDiscards
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getXmitDiscards
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getXmitConstraintErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getXmitConstraintErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getRcvConstraintErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getRcvConstraintErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getLocalLinkIntegrityErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getLocalLinkIntegrityErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getExcessiveBufferOverrunErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getExcessiveBufferOverrunErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getVL15Dropped
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getVL15Dropped
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jibperf_lib_IbNode
 * Method:    getXmitWait
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jibperf_lib_IbNode_getXmitWait
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
