/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter */

#ifndef _Included_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
#define _Included_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getLocalPorts
 * Signature: ()[Lde/hhu/bsinfo/jdetector/lib/IbDiagPerfCounter;
 */
JNIEXPORT jobjectArray JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getLocalPorts
  (JNIEnv *, jclass);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    resetCounters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_resetCounters
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    refreshCounters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_refreshCounters
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getLifespan
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getLifespan
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getRqLocalLengthErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getRqLocalLengthErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getRqLocalProtectionErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getRqLocalProtectionErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getRqLocalQpProtectionErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getRqLocalQpProtectionErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getRqOutOfSequenceErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getRqOutOfSequenceErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getRqRemoteAccessErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getRqRemoteAccessErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getRqRemoteInvalidRequestErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getRqRemoteInvalidRequestErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getRqRnrNakNum
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getRqRnrNakNum
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getRqCompletionQueueEntryErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getRqCompletionQueueEntryErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqBadResponseErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqBadResponseErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqLocalLengthErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqLocalLengthErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqLocalProtectionErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqLocalProtectionErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqLocalQpProtectionErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqLocalQpProtectionErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqMemoryWindowBindErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqMemoryWindowBindErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqOutOfSequenceErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqOutOfSequenceErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqRemoteAccessErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqRemoteAccessErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqRemoteInvalidRequestErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqRemoteInvalidRequestErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqRnrNakNum
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqRnrNakNum
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqRemoteOperationErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqRemoteOperationErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqRnrNakRetriesExceededErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqRnrNakRetriesExceededErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqTransportRetriesExceededErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqTransportRetriesExceededErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    getSqCompletionQueueEntryErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_getSqCompletionQueueEntryErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbDiagPerfCounter_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
