/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_jdetector_lib_IbPort */

#ifndef _Included_de_hhu_bsinfo_jdetector_lib_IbPort
#define _Included_de_hhu_bsinfo_jdetector_lib_IbPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    resetCounters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_resetCounters
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    refreshCounters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_refreshCounters
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getXmitDataBytes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getXmitDataBytes
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getRcvDataBytes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getRcvDataBytes
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getXmitPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getXmitPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getRcvPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getRcvPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getUnicastXmitPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getUnicastXmitPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getUnicastRcvPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getUnicastRcvPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getMulticastXmitPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getMulticastXmitPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getMulticastRcvPkts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getMulticastRcvPkts
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getSymbolErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getSymbolErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getLinkDownedCounter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getLinkDownedCounter
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getLinkRecoveryCounter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getLinkRecoveryCounter
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getRcvErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getRcvErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getRcvRemotePhysicalErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getRcvRemotePhysicalErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getRcvSwitchRelayErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getRcvSwitchRelayErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getXmitDiscards
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getXmitDiscards
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getXmitConstraintErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getXmitConstraintErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getRcvConstraintErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getRcvConstraintErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getLocalLinkIntegrityErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getLocalLinkIntegrityErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getExcessiveBufferOverrunErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getExcessiveBufferOverrunErrors
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getVL15Dropped
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getVL15Dropped
  (JNIEnv *, jobject);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_IbPort
 * Method:    getXmitWait
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_jdetector_lib_IbPort_getXmitWait
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
