/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_jdetector_lib_NativeBuildConfig */

#ifndef _Included_de_hhu_bsinfo_jdetector_lib_NativeBuildConfig
#define _Included_de_hhu_bsinfo_jdetector_lib_NativeBuildConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_jdetector_lib_NativeBuildConfig
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_hhu_bsinfo_jdetector_lib_NativeBuildConfig_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_NativeBuildConfig
 * Method:    getGitRevision
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_hhu_bsinfo_jdetector_lib_NativeBuildConfig_getGitRevision
  (JNIEnv *, jclass);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_NativeBuildConfig
 * Method:    getGitBranch
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_hhu_bsinfo_jdetector_lib_NativeBuildConfig_getGitBranch
  (JNIEnv *, jclass);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_NativeBuildConfig
 * Method:    getBuildDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_hhu_bsinfo_jdetector_lib_NativeBuildConfig_getBuildDate
  (JNIEnv *, jclass);

/*
 * Class:     de_hhu_bsinfo_jdetector_lib_NativeBuildConfig
 * Method:    areAdditionalExtendedCountersEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_hhu_bsinfo_jdetector_lib_NativeBuildConfig_areAdditionalExtendedCountersEnabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
